//! Build script for `ctos`.
//!
//! It scans the `tokenizers/` directory, **gzip-compresses** each tokenizer
//! file into `$OUT_DIR`, and generates `$OUT_DIR/builtin_data.rs` that embeds
//! the compressed bytes via `include_bytes!`. The runtime (tokenizer/builtin.rs)
//! decompresses them on demand. JSON tokenizer files compress ~4-5x, so this
//! shrinks the binary substantially while keeping it fully self-contained.
//!
//! Two file kinds are recognized per key:
//!   * `tokenizer.json`  — a HuggingFace tokenizer (loaded by the `tokenizers` crate)
//!   * `tiktoken.model`  — a tiktoken BPE vocab (loaded by `tiktoken-rs`)
//!
//! Keys with no bundled file are simply omitted, so the crate still compiles
//! when a file is missing and the builtin source reports a clear runtime error.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

use flate2::write::GzEncoder;
use flate2::Compression;

fn gzip(bytes: &[u8]) -> Vec<u8> {
    let mut enc = GzEncoder::new(Vec::new(), Compression::best());
    enc.write_all(bytes).expect("gzip write");
    enc.finish().expect("gzip finish")
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let tok_dir = manifest.join("tokenizers");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    println!("cargo:rerun-if-changed=tokenizers");

    // (key, compressed-file-path-in-OUT_DIR) for each recognized file kind.
    let mut hf_entries: Vec<(String, PathBuf)> = Vec::new();
    let mut tiktoken_entries: Vec<(String, PathBuf)> = Vec::new();

    if tok_dir.is_dir() {
        let mut dirs: Vec<_> = fs::read_dir(&tok_dir)
            .expect("read tokenizers dir")
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for dir in dirs {
            let key = dir
                .file_name()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_default();

            let json = dir.join("tokenizer.json");
            if json.is_file() {
                println!("cargo:rerun-if-changed={}", json.display());
                let raw = fs::read(&json).expect("read tokenizer.json");
                let gz_path = out_dir.join(format!("{key}.tokenizer.json.gz"));
                fs::write(&gz_path, gzip(&raw)).expect("write compressed hf");
                hf_entries.push((key.clone(), gz_path));
            }

            let model = dir.join("tiktoken.model");
            if model.is_file() {
                println!("cargo:rerun-if-changed={}", model.display());
                let raw = fs::read(&model).expect("read tiktoken.model");
                let gz_path = out_dir.join(format!("{key}.tiktoken.model.gz"));
                fs::write(&gz_path, gzip(&raw)).expect("write compressed tiktoken");
                tiktoken_entries.push((key, gz_path));
            }
        }
    }

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit.\n");
    code.push_str("// Values are GZIP-compressed; decompress before use.\n");

    // HuggingFace tokenizer.json (compressed).
    code.push_str("#[allow(clippy::match_single_binding, clippy::all)]\n");
    code.push_str("pub fn builtin_tokenizer_gz(key: &str) -> Option<&'static [u8]> {\n");
    code.push_str("    match key {\n");
    for (key, path) in &hf_entries {
        code.push_str(&format!(
            "        {:?} => Some(include_bytes!({:?}) as &'static [u8]),\n",
            key,
            path.to_string_lossy()
        ));
    }
    code.push_str("        _ => None,\n    }\n}\n\n");

    // tiktoken.model (compressed).
    code.push_str("#[allow(clippy::match_single_binding, clippy::all)]\n");
    code.push_str("pub fn builtin_tiktoken_model_gz(key: &str) -> Option<&'static [u8]> {\n");
    code.push_str("    match key {\n");
    for (key, path) in &tiktoken_entries {
        code.push_str(&format!(
            "        {:?} => Some(include_bytes!({:?}) as &'static [u8]),\n",
            key,
            path.to_string_lossy()
        ));
    }
    code.push_str("        _ => None,\n    }\n}\n\n");

    // Union of all bundled keys (either file kind), for diagnostics.
    let mut keys: Vec<String> = hf_entries
        .iter()
        .map(|(k, _)| k.clone())
        .chain(tiktoken_entries.iter().map(|(k, _)| k.clone()))
        .collect();
    keys.sort();
    keys.dedup();

    code.push_str("pub const BUILTIN_KEYS: &[&str] = &[");
    for key in &keys {
        code.push_str(&format!("{key:?}, "));
    }
    code.push_str("];\n");

    fs::write(out_dir.join("builtin_data.rs"), code).expect("write builtin_data.rs");
}
