//! Build script for `ctos`.
//!
//! It scans the `tokenizers/` directory and generates
//! `$OUT_DIR/builtin_data.rs`, embedding the tokenizer files that are actually
//! present via `include_bytes!`. Two file kinds are recognized per key:
//!   * `tokenizer.json`  — a HuggingFace tokenizer (loaded by the `tokenizers` crate)
//!   * `tiktoken.model`  — a tiktoken BPE vocab (loaded by `tiktoken-rs`)
//!
//! Keys with no bundled file are simply omitted, so:
//!   * when a file is vendored, the resulting binary is fully self-contained and
//!     works offline (the hard requirement from the spec);
//!   * when it is missing, the crate still compiles and the builtin source
//!     reports a clear, actionable runtime error instead of failing the build.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let tok_dir = manifest.join("tokenizers");
    println!("cargo:rerun-if-changed=tokenizers");

    let out_path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("builtin_data.rs");

    // (key, path) for each recognized file kind.
    let mut hf_entries: Vec<(String, PathBuf)> = Vec::new();
    let mut tiktoken_entries: Vec<(String, PathBuf)> = Vec::new();

    if tok_dir.is_dir() {
        let mut dirs: Vec<_> = fs::read_dir(&tok_dir)
            .expect("read tokenizers dir")
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for dir in dirs {
            let key = dir
                .file_name()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_default();

            let json = dir.join("tokenizer.json");
            if json.is_file() {
                println!("cargo:rerun-if-changed={}", json.display());
                hf_entries.push((key.clone(), json));
            }

            let model = dir.join("tiktoken.model");
            if model.is_file() {
                println!("cargo:rerun-if-changed={}", model.display());
                tiktoken_entries.push((key, model));
            }
        }
    }

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit.\n");

    // HuggingFace tokenizer.json bytes.
    code.push_str("#[allow(clippy::match_single_binding, clippy::all)]\n");
    code.push_str("pub fn builtin_tokenizer_bytes(key: &str) -> Option<&'static [u8]> {\n");
    code.push_str("    match key {\n");
    for (key, path) in &hf_entries {
        code.push_str(&format!(
            "        {:?} => Some(include_bytes!({:?}) as &'static [u8]),\n",
            key,
            path.to_string_lossy()
        ));
    }
    code.push_str("        _ => None,\n    }\n}\n\n");

    // tiktoken.model bytes.
    code.push_str("#[allow(clippy::match_single_binding, clippy::all)]\n");
    code.push_str("pub fn builtin_tiktoken_model_bytes(key: &str) -> Option<&'static [u8]> {\n");
    code.push_str("    match key {\n");
    for (key, path) in &tiktoken_entries {
        code.push_str(&format!(
            "        {:?} => Some(include_bytes!({:?}) as &'static [u8]),\n",
            key,
            path.to_string_lossy()
        ));
    }
    code.push_str("        _ => None,\n    }\n}\n\n");

    // Union of all bundled keys (either file kind), for diagnostics.
    let mut keys: Vec<String> = hf_entries
        .iter()
        .map(|(k, _)| k.clone())
        .chain(tiktoken_entries.iter().map(|(k, _)| k.clone()))
        .collect();
    keys.sort();
    keys.dedup();

    code.push_str("pub const BUILTIN_KEYS: &[&str] = &[");
    for key in &keys {
        code.push_str(&format!("{key:?}, "));
    }
    code.push_str("];\n");

    fs::write(&out_path, code).expect("write builtin_data.rs");
}
